/* =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */
/*  »Project«   Teikitu Gaming System (TgS) (∂)
    »File«      TgS Common - Geometry 3D - Triangle [Collision].c_inc
    »Author«    Andrew Aye (mailto: andrew.aye@teikitu.com, https://www.andrew.aye.page)
    »Version«   5.17 / »GUID« 3ED3C595-046B-47FB-8785-5C167178CD24 */
/*  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
/*  Copyright: © 2002-2020, Andrew Aye.  All Rights Reserved.
    This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation,
    either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
    the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the
    GNU Affero General Public License along with this program.  If not, see <https://www.gnu.org/licenses/>. */
/* =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */
#if defined (TGS_COMMON_GEOMETRY_H)

#if !defined (ENABLE_RELOAD_GUARD)
    #define TEMPLATE__VECTOR_DIM 4
    #define ENABLE_RELOAD_GUARD
    #if !defined(TEMPLATE__TYPE_SIZE)
        #if TgCOMPILE__NON_NATIVE_VECTOR_AS_NATIVE
            #define TEMPLATE__TYPE_SIZE 64
            #include __FILE__
            #undef TEMPLATE__TYPE_SIZE
        #endif
        #define TEMPLATE__TYPE_SIZE 32
    #endif
    #undef ENABLE_RELOAD_GUARD
#endif

#include "TgS COMMON/TgS Common - Base - Defines [Template] [Math].h_inc"

/* == Common ===================================================================================================================================================================== */

/* ---- FCN_VO(tgGM_CT_Is_Point_Culled) ------------------------------------------------------------------------------------------------------------------------------------------ */
/* ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
TgBOOL FCN_VO(tgGM_CT_Is_Point_Culled)( VEC_OBJ_T(TgCTRI,CPCU) psCT1, VAR_T(C) fT0, VAR_T(C) fT1 )
{
    /*  Check the barycentric co-ordinates for this point against the validity of the triangle's features.  If its within a margin of error of an ignored feature */
    /* (vertex, edge) then return the point as invalid. */

    /* Edge generated by vertex 0 and vertex 1 */
    if (!FCN_VO(tgGM_CT_Test_Edge_0)( psCT1) && FCN_F(tgCM_NR0)(FCN_F(tgPM_ABS)( fT1 )) )
    {
        if (FCN_VO(tgGM_CT_Test_Point_0)( psCT1) && FCN_F(tgCM_NR0)(FCN_F(tgPM_ABS)( fT0 )) )
        {
            return (true);
        }

        if (FCN_VO(tgGM_CT_Test_Point_1)( psCT1) && FCN_F(tgCM_NR0)(FCN_F(tgPM_ABS)( fT0 - TYPE_K(1 ))) )
        {
            return (true);
        }

        return (false);
    }

    /* Edge generated by vertex 0 and vertex 2 */
    if (!FCN_VO(tgGM_CT_Test_Edge_2)( psCT1) && FCN_F(tgCM_NR0)(FCN_F(tgPM_ABS)( fT0 )) )
    {
        if (FCN_VO(tgGM_CT_Test_Point_0)( psCT1) && FCN_F(tgCM_NR0)(FCN_F(tgPM_ABS)( fT1 )) )
        {
            return (true);
        }

        if (FCN_VO(tgGM_CT_Test_Point_2)( psCT1) && FCN_F(tgCM_NR0)(FCN_F(tgPM_ABS)( fT1 - TYPE_K(1 ))) )
        {
            return (true);
        }

        return (false);
    }

    /* Edge generated by vertex 1 and vertex 2 */
    if (!FCN_VO(tgGM_CT_Test_Edge_1)( psCT1) && FCN_F(tgCM_NR0)(FCN_F(tgPM_ABS)( fT0 + fT1 - TYPE_K(1 ))) )
    {
        if (FCN_VO(tgGM_CT_Test_Point_1)( psCT1) && FCN_F(tgCM_NR0)(FCN_F(tgPM_ABS)( fT1 )) )
        {
            return (true);
        }

        if (FCN_VO(tgGM_CT_Test_Point_2)( psCT1) && FCN_F(tgCM_NR0)(FCN_F(tgPM_ABS)( fT0 )) )
        {
            return (true);
        }

        return (false);
    }

    return (true);
}


/* =============================================================================================================================================================================== */

#include "TgS COMMON/TgS Common - Base - Defines [Template] [Math].h_inc"

/*# defined (TGS_COMMON_GEOMETRY_H) */
#endif
